[openid][stable-3_4_0] #1 Initial Commit - port to stable-3_4_0
pkp/openid pull request #3
Opened 2024-05-23 17:21 UTC by defstat

2024-05-28 21:50 UTC, asmecher requested changes
Just a few comments, thanks!

2024-05-29 07:11 UTC, defstat commented on OpenIDPlugin.php
> + * Copyright (c) 2020 Leibniz Institute for Psychology Information (https://leibniz-psychology.org/)
For existing files I updated the copyright to 

```
 * Copyright (c) 2020 Leibniz Institute for Psychology Information (https://leibniz-psychology.org/)
 * Copyright (c) 2024 Simon Fraser University
 * Copyright (c) 2024 John Willinsky
 * Distributed under the GNU GPL v3. For full terms see the file LICENSE.
```

For new files (like `classes/ContextData.php`) I added the copyright:

```
 * Copyright (c) 2024 Simon Fraser University
 * Copyright (c) 2024 John Willinsky
 * Distributed under the GNU GPL v3. For full terms see the file LICENSE.
```

2024-05-29 07:13 UTC, defstat commented on OpenIDPlugin.php
> + * @ingroup plugins_generic_openid
Removed it from all files

2024-05-29 07:19 UTC, defstat commented on handler/OpenIDHandler.php
> +	public static function getOpenIDSettings(OpenIDPlugin $plugin, int $contextId): ?array
Moved to `OpenIDPlugin` and updated the referencing code

2024-06-05 23:12 UTC, merged